language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install gcc-multilib g++-multilib -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install buddy
  - haxelib install utest
  - haxelib install hxcpp
  - haxelib git cocktail-dom-event https://github.com/haxecocktail/cocktail-dom-event
  - haxelib git cocktail-dom https://github.com/haxecocktail/cocktail-dom
  - haxelib git cocktail-cssom https://github.com/haxecocktail/cocktail-cssom
  - mkdir build

script:
  - make run-tests
